theme = "ansi"

[editor]
line-number = "relative"
color-modes = true
bufferline = "multiple"
# cursorline = true
popup-border = "all"
# rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["version-control", "spacer", "separator", "file-type"]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "selections",
  "register",
  "file-encoding",
]
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"

[keys.insert]
"C-space" = "completion"

[keys.normal]
D = "kill_to_line_end"
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
S-l = ":buffer-next"
S-h = ":buffer-previous"

[keys.normal.g]
q = ":reflow" # Reflow

[keys.normal.space]
q = ":quit"  # Quit
w = ":write" # Write buffer
