# ANSI Terminal theme
# Author: Andrew Carter <@ascarter>

# Uses only ANSI terminal 16 color values for portability
# Optimized for color sensitive users
# Adapts to dark or light terminal if terminal theme adapts
# Recommend using Apple terminal theme that uses dynamic colors
# for text, background and accents

# -------------------
# UI
# -------------------

"ui.cursor" = { modifiers = ["reversed" ] }

"ui.cursorline.primary" = { underline = { color = "light-blue", style = "line" } }
"ui.cursorcolumn.primary" = { fg = "light-gray", bg = "default", modifiers = ["reversed"] }

"ui.gutter" = { bg = "default" }
"ui.gutter.selected" = { bg = "default", modifiers = ["bold"] }

"ui.linenr" = { modifiers = ["dim"] }
"ui.linenr.selected" = { modifiers = ["bold"] }

"ui.selection" = { bg = "light-blue" }

"ui.debug.breakpoint" = { fg = "red", modifiers = ["bold"] }
"ui.debug.active" = { fg = "yellow", modifiers = ["bold"] }

"ui.statusline" = { bg = "default", modifiers = ["bold"] }
"ui.statusline.separator" = { modifiers = ["dim"] }
"ui.statusline.inactive" = { bg = "default", modifiers = ["dim"] }
"ui.statusline.normal" = { modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "white", bg = "light-blue", modifiers = ["bold"] }

"ui.menu.selected" = { fg = "light-blue", bg = "default", modifiers = ["reversed"] }
"ui.menu.scroll" = { fg = "blue", bg = "light-gray" }

"ui.highlight" = { fg = "yellow", bg = "light-blue", modifiers = ["italic"] }
"ui.text.focus" = { modifiers = ["bold"] }
"ui.text.inactive" = { modifiers = ["dim"] }

"ui.help" = { fg = "default", bg = "default" }
"ui.window" = { fg = "light-gray", bg = "default", modifiers = ["dim"] }

"ui.virtual" = { fg = "light-gray", modifiers = ["dim"] }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = { fg = "gray", bg = "default", modifiers = ["dim"] }
"ui.virtual.indent-guide" = { fg = "light-gray", modifiers = ["dim"] }
"ui.virtual.inlay-hint" = { bg = "light-gray" }

warning = "yellow"
error = "red"
info = "blue"
hint = "gray"

"diagnostic" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "gray", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

# -------------------
# Syntax Highlighting
# -------------------

# Match tree-sitter scopes
comment = { modifiers = ["dim","italic"] }
constant = { modifiers = ["italic"] }
"function.special" = { modifiers = ["italic"] }
label = { fg = "blue", modifiers = ["bold"] }
namespace = { modifiers = ["bold"] }
"string.regexp" = { modifiers = ["bold"] }
"string.special" = { modifiers = ["bold"] }
tag = { fg = "blue", modifiers = ["bold"] }

# markup
"markup.heading" = { modifiers = ["bold"] }
"markup.list" = { modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["dim", "crossed_out"] }
"markup.link" = { fg = "blue", modifiers = ["underline"] }
"markup.quote" = { modifiers = ["italic"] }
"markup.raw.block" = { modifiers = ["dim"] }
"markup.raw.inline" = { modifiers = ["dim"] }

# diff
"diff" = "default"
"diff.plus" = { modifiers = ["bold"] }
"diff.minus" = { fg = "red", modifiers = ["bold"] }
"diff.delta" = { modifiers = ["bold", "italic"] }
"diff.plus.gutter" = "blue"
"diff.minus.gutter" = "red"
"diff.delta.gutter" = "yellow"

# -------------------
# Color Palette
# -------------------

# ANSI Color Names
#
# Idx  Name
# ---  -----------
#  -   default
#  0   black
#  1   red
#  2   green
#  3   yellow
#  4   blue
#  5   magenta
#  6   cyan
#  7   light-gray
#  8   gray
#  9   light-red
# 10   light-green
# 11   light-yellow
# 12   light-blue
# 13   light-magenta
# 14   light-cyan
# 15   white
